### ISSUE TITLE
Cannot implicitly convert type `UnityEngine.Coroutine' to `Coroutine'

### ISSUE THREAD

**Issue by BANZBOWINKEL** [laurenth-unity/lightmap-switching-tool#22]
Hey Laurenth,
sorry to bother but I get this error when importing the LevelLightmapData-script into my project:

Assets/LevelLightmapData.cs(73,38): error CS0029: Cannot implicitly convert type `UnityEngine.Coroutine' to `Coroutine'

Any idea why this is? Didn't change a thing and in a fresh testproject it is working, too.
I am working on 2018.2.2f1

Thank you in advance for any help and best,
Friedemann

**Comment by BANZBOWINKEL** [comment]
My bad!!
Had a script that I used to test called "Coroutines" in my project :P
Hard to be a noob...

Can you delete this, laurenth? Sorry!!
Best, Friedemann

**Comment by laurenth-unity** [comment]
Ok, no problem :)
